// import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "@/components";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Car-Rental",
  description: "Generated By Ronnie Ahmed",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
